java -Dfile.encoding=utf8 -Duser.timezone=GMT -jar ./crawlego-1.0.0-m8.jar "./01.adiga-get-univ.xml" "A=A"
java -Dfile.encoding=utf8 -Duser.timezone=GMT -jar ./crawlego-1.0.0-m8.jar "./02.adiga-get-division.xml" "A=A"
java -Dfile.encoding=utf8 -Duser.timezone=GMT -jar ./crawlego-1.0.0-m8.jar "./03-1.adiga-get-result01.xml" "A=A"
java -Dfile.encoding=utf8 -Duser.timezone=GMT -jar ./crawlego-1.0.0-m8.jar "./03-2.adiga-get-result02.xml" "A=A"
java -Dfile.encoding=utf8 -Duser.timezone=GMT -jar ./crawlego-1.0.0-m8.jar "./04.adiga-mgr-data.xml" "A=A"
